(()=>{
const planner=document.querySelector('#planner');if(!planner)return;
const $=selector=>document.querySelector(selector),labels={path:'FOLLOW PATH／執行路徑',wait:'WAIT／等待'};
let commands=[],pathNames=[],namedCommands=[];
function setView(view){planner.classList.toggle('auto-editing',view==='auto');planner.classList.toggle('commands-editing',view==='commands');document.querySelectorAll('[data-planner-view]').forEach(button=>button.classList.toggle('active',button.dataset.plannerView===view));$('#autoBuilder').hidden=view!=='auto';$('#commandLibrary').hidden=view!=='commands';if(view==='auto')loadPaths()}
document.querySelectorAll('[data-planner-view]').forEach(button=>button.onclick=()=>setView(button.dataset.plannerView));
async function loadPaths(){try{const response=await fetch('/api/paths'),data=await response.json();pathNames=data.paths||[]}catch{pathNames=[]}render()}
async function loadCommandRegistry(){try{const response=await fetch('/api/auto-commands'),data=await response.json();namedCommands=data.commands||[]}catch{namedCommands=[]}for(const command of namedCommands)labels[command.id]=`${command.english}／${command.chinese}`;const palette=$('#namedCommandPalette');palette.innerHTML=namedCommands.map(command=>`<button data-add-auto="${escapeHtml(command.id)}">${escapeHtml(command.english)}<small>${escapeHtml(command.chinese)}</small></button>`).join('');palette.querySelectorAll('[data-add-auto]').forEach(button=>button.onclick=()=>add(button.dataset.addAuto));$('#commandLibraryGrid').innerHTML=namedCommands.map((command,index)=>`<article class="command-library-card"><small>${String(index+1).padStart(2,'0')}</small><b>${escapeHtml(command.english)}／${escapeHtml(command.chinese)}</b><code>${escapeHtml(command.cpp)}</code><p>${escapeHtml(command.id)} · ${escapeHtml(command.symbol)}</p></article>`).join('');render()}
function add(type){commands.push(type==='path'?{type,pathName:pathNames[0]||''}:type==='wait'?{type,seconds:.25}:{type});render()}
document.querySelectorAll('[data-add-auto]').forEach(button=>button.onclick=()=>add(button.dataset.addAuto));
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function editor(command,index){if(command.type==='path')return`<label>Path <select data-path-index="${index}">${pathNames.length?pathNames.map(name=>`<option value="${escapeHtml(name)}"${name===command.pathName?' selected':''}>${escapeHtml(name)}</option>`).join(''):'<option value="">NO SAVED PATH／尚無路徑</option>'}</select></label>`;if(command.type==='wait')return`<label>Seconds／秒 <input data-wait-index="${index}" type="number" min="0" max="30" step="0.05" value="${command.seconds}"></label>`;return'<span>Named Command／已註冊動作</span>'}
function render(){const list=$('#autoCommandList');list.innerHTML=commands.length?commands.map((command,index)=>`<article class="auto-command-card"><div><strong>${labels[command.type]||`UNKNOWN／未註冊：${escapeHtml(command.type)}`}</strong>${editor(command,index)}</div><div class="auto-card-actions"><button data-up="${index}" title="Move up">↑</button><button data-down="${index}" title="Move down">↓</button><button data-remove="${index}" title="Delete">×</button></div></article>`).join(''):'<div class="auto-command-empty">SELECT A COMMAND ON THE LEFT<br>從左側加入第一個動作</div>';$('#autoStepCount').textContent=`${commands.length} COMMANDS`;$('#autoCppPreview').textContent=`void autonomous()\n{\n  runAuto("${($('#autoName').value||'untitled-auto').replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()}");\n}`;list.querySelectorAll('[data-path-index]').forEach(select=>select.onchange=()=>{commands[+select.dataset.pathIndex].pathName=select.value;render()});list.querySelectorAll('[data-wait-index]').forEach(input=>input.onchange=()=>{commands[+input.dataset.waitIndex].seconds=Math.max(0,Math.min(30,Number(input.value)||0));render()});list.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{commands.splice(+button.dataset.remove,1);render()});list.querySelectorAll('[data-up]').forEach(button=>button.onclick=()=>move(+button.dataset.up,-1));list.querySelectorAll('[data-down]').forEach(button=>button.onclick=()=>move(+button.dataset.down,1));localStorage.setItem('vex-auto-draft',JSON.stringify({name:$('#autoName').value,commands}))}
function move(index,direction){const target=index+direction;if(target<0||target>=commands.length)return;[commands[index],commands[target]]=[commands[target],commands[index]];render()}
function updateRobotEntry(){const safeName=($('#autoName').value||'untitled-auto').replace(/[^a-z0-9_-]+/gi,'-').toLowerCase();$('#autoRobotEntry').textContent=`runAuto("${safeName}");`}
$('#autoName').oninput=()=>{render();updateRobotEntry()};
$('#autoSave').onclick=async()=>{const status=$('#autoBuilderStatus');if(!commands.length){status.textContent='Add at least one command／至少加入一個動作';return}status.textContent='Saving Auto／正在儲存…';try{const response=await fetch('/api/auto',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:1,name:$('#autoName').value,commands})}),result=await response.json();status.textContent=response.ok?`Saved／已儲存：${result.json} + ${result.header}`:`Error／錯誤：${result.error}`}catch{status.textContent='Simulator server unavailable／模擬器伺服器未連線'}};
try{const draft=JSON.parse(localStorage.getItem('vex-auto-draft'));if(draft){$('#autoName').value=draft.name||'skills-auto';commands=Array.isArray(draft.commands)?draft.commands:[]}}catch{}
loadCommandRegistry();render();updateRobotEntry();
})();
