(()=>{
const field=document.querySelector('#pathField');
if(!field)return;
const svgNs='http://www.w3.org/2000/svg';
const goals=[[16.7,33.3],[16.7,66.7],[33.3,16.7],[66.7,16.7],[50,50],[33.3,83.3],[66.7,83.3],[83.3,33.3],[83.3,66.7]];
window.drawOverrideFieldLayer?.('#pathGoals');
const elements={name:document.querySelector('#pathName'),driveType:document.querySelector('#pathDriveType'),status:document.querySelector('#pathStatus'),path:document.querySelector('#plannedPath'),trail:document.querySelector('#pathPreviewTrail'),robot:document.querySelector('#pathPreviewRobot'),selectedRobot:document.querySelector('#pathSelectedRobot'),swept:document.querySelector('#pathSweptFootprints'),collision:document.querySelector('#pathCollisionStatus'),robotWidth:document.querySelector('#robotWidth'),robotLength:document.querySelector('#robotLength'),points:document.querySelector('#pathWaypoints'),tangentControl:document.querySelector('#pathTangentControl'),x:document.querySelector('#pointX'),y:document.querySelector('#pointY'),tangent:document.querySelector('#pointTangent'),tangentText:document.querySelector('#pointTangentText'),tangentStrength:document.querySelector('#pointTangentStrength'),tangentStrengthText:document.querySelector('#pointTangentStrengthText'),tangentAuto:document.querySelector('#pointTangentAuto'),heading:document.querySelector('#pointHeading'),headingText:document.querySelector('#pointHeadingText'),velocity:document.querySelector('#pointVelocity'),velocityText:document.querySelector('#pointVelocityText'),selected:document.querySelector('#selectedPointLabel'),remove:document.querySelector('#pointDelete'),preview:document.querySelector('#pathCppPreview')};
let points=[],selectedIndex=-1,dragging=false,draggingTangent=false,showFootprints=false,previewAnimation=0,previewDistance=0,previewLastTime=0,previewTrail=[];

for(let y=0;y<6;y++)for(let x=0;x<6;x++){const tile=document.createElementNS(svgNs,'rect');tile.setAttribute('class','tile');tile.setAttribute('x',x*100/6);tile.setAttribute('y',y*100/6);tile.setAttribute('width',100/6);tile.setAttribute('height',100/6);document.querySelector('#pathTiles').append(tile)}
for(const [x,y] of goals){const goal=document.createElementNS(svgNs,'circle');goal.setAttribute('class','goal');goal.setAttribute('cx',x);goal.setAttribute('cy',y);goal.setAttribute('r',3.5);document.querySelector('#pathGoals').append(goal)}

const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const svgPoint=event=>{const bounds=field.getBoundingClientRect();return{x:clamp((event.clientX-bounds.left)/bounds.width*100,0,100),y:clamp((event.clientY-bounds.top)/bounds.height*100,0,100)}};
const isTankDrive=()=>elements.driveType.value==='tank';
// 第一點代表 Starting Pose，起始車頭不可被第二點的位置反向改寫。
// 中間與終點維持自動切線，使用者仍可透過 tangentDeg 手動覆寫。
const automaticTangentHeading=index=>{if(index===0||points.length<2)return points[index]?.headingDeg||0;const previous=points[Math.max(0,index-1)],next=points[Math.min(points.length-1,index+1)];return Math.atan2(next.x-previous.x,-(next.y-previous.y))*180/Math.PI};
const waypointTangentHeading=index=>Number.isFinite(points[index]?.tangentDeg)?points[index].tangentDeg:automaticTangentHeading(index);
const effectiveWaypointHeading=index=>isTankDrive()?waypointTangentHeading(index):points[index]?.headingDeg||0;
const toFieldPoint=(p,index=-1)=>({xIn:+(p.x*1.44).toFixed(2),yIn:+((100-p.y)*1.44).toFixed(2),headingDeg:+(index>=0?effectiveWaypointHeading(index):p.headingDeg).toFixed(2),velocityPct:p.velocityPct,tangentDeg:Number.isFinite(p.tangentDeg)?+p.tangentDeg.toFixed(2):null,resolvedTangentDeg:+(index>=0?waypointTangentHeading(index):(p.resolvedTangentDeg??p.headingDeg)).toFixed(2),tangentStrength:p.tangentStrength||100});
const fromFieldPoint=p=>({x:clamp(p.xIn/1.44,0,100),y:clamp(100-p.yIn/1.44,0,100),headingDeg:clamp(Number(p.headingDeg)||0,-180,180),velocityPct:clamp(Number(p.velocityPct)||60,10,100),tangentDeg:Number.isFinite(p.tangentDeg)?clamp(Number(p.tangentDeg),-180,180):null,tangentStrength:clamp(Number(p.tangentStrength)||100,20,180)});

function smoothPath(values){if(values.length<2)return'';let d=`M${values[0].x.toFixed(2)} ${values[0].y.toFixed(2)}`;for(let i=0;i<values.length-1;i++){const start=values[i],end=values[i+1],distance=Math.hypot(end.x-start.x,end.y-start.y),startAngle=waypointTangentHeading(i)*Math.PI/180,endAngle=waypointTangentHeading(i+1)*Math.PI/180,startHandle=distance/3*(start.tangentStrength||100)/100,endHandle=distance/3*(end.tangentStrength||100)/100,c1x=start.x+Math.sin(startAngle)*startHandle,c1y=start.y-Math.cos(startAngle)*startHandle,c2x=end.x-Math.sin(endAngle)*endHandle,c2y=end.y+Math.cos(endAngle)*endHandle;d+=` C${c1x.toFixed(2)} ${c1y.toFixed(2)} ${c2x.toFixed(2)} ${c2y.toFixed(2)} ${end.x.toFixed(2)} ${end.y.toFixed(2)}`}return d}
function cppPreview(){const rows=points.map((point,index)=>{const p=toFieldPoint(point,index);return`  {${p.xIn.toFixed(2)}, ${p.yIn.toFixed(2)}, ${p.headingDeg.toFixed(1)}, ${p.velocityPct.toFixed(1)}}`});return rows.length?`generatedPath::points = {\n${rows.join(',\n')}\n};`:'// Add points on the field.'}
function stopPreview(reset=true){if(previewAnimation)cancelAnimationFrame(previewAnimation);previewAnimation=0;previewLastTime=0;if(reset){previewDistance=0;previewTrail=[];elements.trail.setAttribute('d','');elements.robot.setAttribute('hidden','');elements.status.textContent='Click field to add points／點擊增加路徑點'}}
function previewStateAt(progress){
  if(points.length===1)return{heading:points[0].headingDeg,velocity:points[0].velocityPct};
  const lengths=[0];let total=0;for(let index=1;index<points.length;index++){total+=Math.hypot(points[index].x-points[index-1].x,points[index].y-points[index-1].y);lengths.push(total)}
  const target=progress*(total||1);let segment=0;while(segment<lengths.length-2&&target>lengths[segment+1])segment++;
  const local=(target-lengths[segment])/Math.max(.001,lengths[segment+1]-lengths[segment]);const start=points[segment],end=points[segment+1];
  const headingDelta=((end.headingDeg-start.headingDeg+540)%360)-180;
  const holonomicHeading=start.headingDeg+headingDelta*local;
  return{heading:isTankDrive()?pathTangentHeading(progress):holonomicHeading,velocity:start.velocityPct+(end.velocityPct-start.velocityPct)*local};
}
function pathTangentHeading(progress){const total=elements.path.getTotalLength();if(!total)return points[0]?.headingDeg||0;const distance=clamp(progress,0,1)*total,offset=Math.min(.35,total/2),before=elements.path.getPointAtLength(Math.max(0,distance-offset)),after=elements.path.getPointAtLength(Math.min(total,distance+offset));return Math.atan2(after.x-before.x,-(after.y-before.y))*180/Math.PI}
function robotSize(){return{width:clamp(Number(elements.robotWidth.value)||18,6,24)/1.44,length:clamp(Number(elements.robotLength.value)||18,6,24)/1.44}}
function collisionAt(x,y,heading){
  const size=robotSize(),halfWidth=size.width/2,halfLength=size.length/2,radians=heading*Math.PI/180,cosine=Math.cos(radians),sine=Math.sin(radians);
  const extentX=halfWidth*Math.abs(cosine)+halfLength*Math.abs(sine),extentY=halfWidth*Math.abs(sine)+halfLength*Math.abs(cosine);
  if(x-extentX<0||x+extentX>100||y-extentY<0||y+extentY>100)return{type:'wall'};
  for(let index=0;index<goals.length;index++){
    const dx=goals[index][0]-x,dy=goals[index][1]-y,localX=dx*cosine+dy*sine,localY=-dx*sine+dy*cosine;
    const closestX=clamp(localX,-halfWidth,halfWidth),closestY=clamp(localY,-halfLength,halfLength);
    if(Math.hypot(localX-closestX,localY-closestY)<3.5)return{type:'goal',index};
  }
  return null;
}
function configureRobot(group,x,y,heading,collision){
  const size=robotSize(),rect=group.querySelector('.robot-body'),arrow=group.querySelector('.robot-front'),wheels=[...group.querySelectorAll('.robot-wheel')],wheelWidth=Math.max(.7,size.width*.09),wheelLength=Math.max(1.8,size.length*.28);rect.setAttribute('x',-size.width/2);rect.setAttribute('y',-size.length/2);rect.setAttribute('width',size.width);rect.setAttribute('height',size.length);rect.setAttribute('rx','.8');arrow.setAttribute('d',`M-2 ${(-size.length/2+2).toFixed(2)}L0 ${(-size.length/2-1.5).toFixed(2)}L2 ${(-size.length/2+2).toFixed(2)}Z`);wheels.forEach((wheel,index)=>{wheel.setAttribute('width',wheelWidth);wheel.setAttribute('height',wheelLength);wheel.setAttribute('x',index%2===0?-size.width/2-wheelWidth*.45:size.width/2-wheelWidth*.55);wheel.setAttribute('y',index<2?-size.length*.38:size.length*.1)});group.setAttribute('transform',`translate(${x} ${y}) rotate(${heading})`);group.classList.toggle('colliding',Boolean(collision));group.removeAttribute('hidden');
}
function configureTangentControl(){const point=points[selectedIndex];if(!point){elements.tangentControl.setAttribute('hidden','');return}const angle=waypointTangentHeading(selectedIndex)*Math.PI/180,strength=point.tangentStrength||100,handleLength=7+strength*.055,x=Math.sin(angle)*handleLength,y=-Math.cos(angle)*handleLength,line=elements.tangentControl.querySelector('line'),handle=elements.tangentControl.querySelector('circle');elements.tangentControl.setAttribute('transform',`translate(${point.x} ${point.y})`);line.setAttribute('x2',x);line.setAttribute('y2',y);handle.setAttribute('cx',x);handle.setAttribute('cy',y);elements.tangentControl.removeAttribute('hidden')}
function renderSweptFootprints(){
  configureTangentControl();elements.swept.replaceChildren();if(points.length<2){elements.collision.className='path-clear';elements.collision.textContent='CLEAR／路徑未碰撞';return}
  const total=elements.path.getTotalLength(),samples=Math.max(12,Math.ceil(total/3));let firstCollision=null;
  for(let index=0;index<=samples;index++){const progress=index/samples,position=elements.path.getPointAtLength(progress*total),state=previewStateAt(progress),hit=collisionAt(position.x,position.y,state.heading);if(hit&&!firstCollision)firstCollision={...hit,progress};if(showFootprints){const size=robotSize(),rect=document.createElementNS(svgNs,'rect');rect.setAttribute('class','path-swept'+(hit?' colliding':''));rect.setAttribute('x',-size.width/2);rect.setAttribute('y',-size.length/2);rect.setAttribute('width',size.width);rect.setAttribute('height',size.length);rect.setAttribute('transform',`translate(${position.x} ${position.y}) rotate(${state.heading})`);elements.swept.append(rect)}}
  elements.collision.className=firstCollision?'path-collision':'path-clear';elements.collision.textContent=firstCollision?`COLLISION／碰撞 · ${(firstCollision.progress*100).toFixed(0)}% · ${firstCollision.type==='wall'?'WALL／牆壁':`GOAL ${firstCollision.index+1}`}`:'CLEAR／路徑未碰撞';
}
function previewFrame(time){
  const totalLength=elements.path.getTotalLength();if(!previewLastTime)previewLastTime=time;const dt=Math.min((time-previewLastTime)/1000,.05);previewLastTime=time;
  const current=previewStateAt(totalLength?previewDistance/totalLength:0);previewDistance+=dt*(5+current.velocity*.28);
  const progress=Math.min(1,previewDistance/Math.max(.001,totalLength)),position=elements.path.getPointAtLength(progress*totalLength),state=previewStateAt(progress);
  const hit=collisionAt(position.x,position.y,state.heading);configureRobot(elements.robot,position.x,position.y,state.heading,hit);previewTrail.push([position.x,position.y]);elements.trail.setAttribute('d','M'+previewTrail.map(value=>value.map(number=>number.toFixed(2)).join(' ')).join('L'));
  elements.status.textContent=`PREVIEW／預覽 · X ${(position.x*1.44).toFixed(1)} · Y ${((100-position.y)*1.44).toFixed(1)} · H ${state.heading.toFixed(1)}° · V ${state.velocity.toFixed(0)}%${hit?' · COLLISION／碰撞':''}`;
  if(progress<1)previewAnimation=requestAnimationFrame(previewFrame);else{previewAnimation=0;elements.status.textContent+=' · COMPLETE／完成'}
}
function playPreview(){if(points.length<2){elements.status.textContent='Need at least 2 points／至少需要兩點';return}stopPreview(false);previewDistance=0;previewTrail=[];elements.trail.setAttribute('d','');previewAnimation=requestAnimationFrame(previewFrame)}
function render(){elements.path.setAttribute('d',smoothPath(points));elements.points.replaceChildren();points.forEach((point,index)=>{const group=document.createElementNS(svgNs,'g');group.dataset.index=index;group.setAttribute('transform',`translate(${point.x} ${point.y})`);const circle=document.createElementNS(svgNs,'circle');circle.setAttribute('r',2.6);circle.setAttribute('class','path-waypoint'+(index===selectedIndex?' selected':''));const radians=effectiveWaypointHeading(index)*Math.PI/180,line=document.createElementNS(svgNs,'line');line.setAttribute('class','path-heading');line.setAttribute('x2',(Math.sin(radians)*6).toFixed(2));line.setAttribute('y2',(-Math.cos(radians)*6).toFixed(2));const label=document.createElementNS(svgNs,'text');label.setAttribute('class','path-index');label.textContent=String(index+1);group.append(line,circle,label);elements.points.append(group)});const selected=points[selectedIndex],disabled=!selected;for(const control of [elements.x,elements.y,elements.tangent,elements.tangentStrength,elements.tangentAuto,elements.heading,elements.velocity,elements.remove])control.disabled=disabled;elements.heading.disabled=disabled||isTankDrive();if(selected){const tangent=waypointTangentHeading(selectedIndex),heading=effectiveWaypointHeading(selectedIndex),p=toFieldPoint(selected,selectedIndex),hit=collisionAt(selected.x,selected.y,heading);elements.x.value=p.xIn;elements.y.value=p.yIn;elements.tangent.value=Math.round(tangent);elements.tangentStrength.value=selected.tangentStrength||100;elements.tangentText.textContent=Number.isFinite(selected.tangentDeg)?`${tangent.toFixed(1)}°`:`AUTO ${tangent.toFixed(1)}°／自動`;elements.tangentStrengthText.textContent=(selected.tangentStrength||100)+'%';elements.heading.value=isTankDrive()?Math.round(heading):selected.headingDeg;elements.velocity.value=selected.velocityPct;elements.headingText.textContent=isTankDrive()?`TANGENT ${heading.toFixed(1)}°／跟隨切線`:`${selected.headingDeg}°`;elements.velocityText.textContent=selected.velocityPct+'%';elements.selected.textContent=`Point ${selectedIndex+1}／第 ${selectedIndex+1} 點`;configureRobot(elements.selectedRobot,selected.x,selected.y,heading,hit)}else{elements.selected.textContent='No selection／未選取';elements.selectedRobot.setAttribute('hidden','')}renderSweptFootprints();elements.preview.textContent=cppPreview();localStorage.setItem('vex-path-draft',JSON.stringify({name:elements.name.value,drivetrain:elements.driveType.value,robot:{widthIn:Number(elements.robotWidth.value),lengthIn:Number(elements.robotLength.value)},points:points.map(toFieldPoint)}))}
function setSelectedFieldValue(){if(selectedIndex<0)return;const current=points[selectedIndex];points[selectedIndex]=fromFieldPoint({xIn:Number(elements.x.value),yIn:Number(elements.y.value),headingDeg:Number(elements.heading.value),velocityPct:Number(elements.velocity.value),tangentDeg:current.tangentDeg,tangentStrength:current.tangentStrength});render()}

field.addEventListener('pointerdown',event=>{stopPreview();if(event.target.closest?.('#pathTangentControl')){draggingTangent=true;field.setPointerCapture(event.pointerId)}else{const group=event.target.closest?.('g[data-index]');if(group){selectedIndex=Number(group.dataset.index);dragging=true;field.setPointerCapture(event.pointerId)}else{const p=svgPoint(event);points.push({...p,headingDeg:points.at(-1)?.headingDeg||0,velocityPct:60,tangentDeg:null,tangentStrength:100});selectedIndex=points.length-1}render()}});
field.addEventListener('pointermove',event=>{if(selectedIndex<0)return;const cursor=svgPoint(event);if(draggingTangent){const point=points[selectedIndex],dx=cursor.x-point.x,dy=cursor.y-point.y,segment=points.length>1?Math.hypot((points[selectedIndex?selectedIndex-1:1]?.x||point.x)-point.x,(points[selectedIndex?selectedIndex-1:1]?.y||point.y)-point.y):20;point.tangentDeg=Math.atan2(dx,-dy)*180/Math.PI;point.tangentStrength=clamp(Math.hypot(dx,dy)*3/Math.max(1,segment)*100,20,180);render()}else if(dragging){Object.assign(points[selectedIndex],cursor);render()}});
field.addEventListener('pointerup',()=>{dragging=false;draggingTangent=false});field.addEventListener('pointercancel',()=>{dragging=false;draggingTangent=false});
elements.x.onchange=()=>{stopPreview();setSelectedFieldValue()};elements.y.onchange=()=>{stopPreview();setSelectedFieldValue()};elements.tangent.oninput=()=>{if(selectedIndex<0)return;stopPreview();points[selectedIndex].tangentDeg=Number(elements.tangent.value);render()};elements.tangentStrength.oninput=()=>{if(selectedIndex<0)return;stopPreview();points[selectedIndex].tangentStrength=Number(elements.tangentStrength.value);render()};elements.tangentAuto.onclick=()=>{if(selectedIndex<0)return;stopPreview();points[selectedIndex].tangentDeg=null;render()};elements.heading.oninput=()=>{if(selectedIndex<0)return;stopPreview();points[selectedIndex].headingDeg=Number(elements.heading.value);render()};elements.velocity.oninput=()=>{if(selectedIndex<0)return;stopPreview();points[selectedIndex].velocityPct=Number(elements.velocity.value);render()};
elements.remove.onclick=()=>{if(selectedIndex<0)return;stopPreview();points.splice(selectedIndex,1);selectedIndex=Math.min(selectedIndex,points.length-1);render()};
document.querySelector('#pathUndo').onclick=()=>{stopPreview();points.pop();selectedIndex=points.length-1;render()};document.querySelector('#pathNew').onclick=()=>{stopPreview();points=[];selectedIndex=-1;render()};
document.querySelector('#pathPlay').onclick=playPreview;document.querySelector('#pathStop').onclick=()=>stopPreview();

function pathDocument(){return{version:2,name:elements.name.value.trim()||'untitled-path',drivetrain:elements.driveType.value,holonomic:!isTankDrive(),field:{widthIn:144,heightIn:144,origin:'bottom-left',headingZero:'+Y'},robot:{widthIn:Number(elements.robotWidth.value),lengthIn:Number(elements.robotLength.value)},points:points.map(toFieldPoint)}}
document.querySelector('#pathSave').onclick=async()=>{if(points.length<2){elements.status.textContent='Need at least 2 points／至少需要兩點';return}elements.status.textContent='Saving／儲存中…';const response=await fetch('/api/path',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pathDocument())});const result=await response.json();elements.status.textContent=response.ok?`Saved／已儲存：${result.header}`:`Error／錯誤：${result.error}`};
document.querySelector('#pathExport').onclick=()=>{const blob=new Blob([JSON.stringify(pathDocument(),null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=(pathDocument().name||'path')+'.json';link.click();URL.revokeObjectURL(link.href)};
document.querySelector('#pathImport').onchange=async event=>{stopPreview();try{const documentData=JSON.parse(await event.target.files[0].text());elements.name.value=documentData.name||'imported-path';elements.driveType.value=documentData.drivetrain==='mecanum'?'mecanum':'tank';elements.robotWidth.value=documentData.robot?.widthIn||18;elements.robotLength.value=documentData.robot?.lengthIn||18;points=(documentData.points||[]).map(fromFieldPoint);selectedIndex=points.length?0:-1;render();elements.status.textContent='Imported／已匯入'}catch{elements.status.textContent='Invalid JSON／JSON 格式錯誤'}event.target.value=''};
elements.name.oninput=render;elements.driveType.onchange=()=>{stopPreview();render()};elements.robotWidth.onchange=()=>{stopPreview();render()};elements.robotLength.onchange=()=>{stopPreview();render()};
document.querySelector('#pathFocus').onclick=()=>{const planner=document.querySelector('#planner'),active=planner.classList.toggle('field-focus');document.querySelector('#pathFocus').textContent=active?'⊟ EXIT FOCUS／返回設定':'⛶ FIELD FOCUS／場地放大'};
document.querySelector('#pathFootprintsToggle').onclick=()=>{showFootprints=!showFootprints;const button=document.querySelector('#pathFootprintsToggle');button.setAttribute('aria-pressed',String(showFootprints));button.textContent=showFootprints?'FOOTPRINTS ON／外框開啟':'FOOTPRINTS OFF／外框關閉';render()};
try{const draft=JSON.parse(localStorage.getItem('vex-path-draft'));if(draft?.points?.length){elements.name.value=draft.name||'skills-path';elements.driveType.value=draft.drivetrain==='mecanum'?'mecanum':'tank';elements.robotWidth.value=draft.robot?.widthIn||18;elements.robotLength.value=draft.robot?.lengthIn||18;points=draft.points.map(fromFieldPoint);selectedIndex=0}}catch{}
render();
})();
